# Generated by Django 4.1.4 on 2022-12-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetToken',
        ),
    ]
