# Generated by Django 4.1.4 on 2022-12-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_resettoken_created_at_resettoken_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
