# Generated by Django 4.1.4 on 2022-12-15 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=255)),
                ('specific_experience', models.JSONField()),
                ('specific_questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
