# Generated by Django 4.1.4 on 2022-12-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
