# Generated by Django 4.1.4 on 2022-12-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True)),
                ('min_experience', models.CharField(max_length=255)),
                ('max_experience', models.CharField(max_length=255)),
                ('salary_min_lpa', models.CharField(max_length=255)),
                ('salary_max_lpa', models.CharField(max_length=255)),
                ('total_position', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
