# Generated by Django 4.1.4 on 2022-12-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0008_scheduleinterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleinterview',
            name='interview_date',
            field=models.DateTimeField(null=True),
        ),
    ]
