# Generated by Django 4.1.4 on 2022-12-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0009_alter_scheduleinterview_interview_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleInterview',
        ),
    ]
