# Generated by Django 4.1.4 on 2022-12-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0010_delete_scheduleinterview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_ctc', models.CharField(max_length=100)),
                ('expected_ctc', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('interview_date', models.DateTimeField(null=True)),
                ('expiry_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('SELECTED', 'SELECTED'), ('REJECTED', 'REJECTED'), ('BLACKLISTED', 'BLACKLISTED'), ('UNDERPROCESS', 'UNDERPROCESS')], default='UNDERPROCESS', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.job')),
            ],
        ),
    ]
