# Generated by Django 4.1.4 on 2022-12-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0011_scheduleinterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleinterview',
            name='interview_date',
            field=models.DateField(null=True),
        ),
    ]
