# Generated by Django 4.1.4 on 2022-12-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0012_alter_scheduleinterview_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobtitle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
